/* Copyright 2012-2013 The Pennsylvania State University
 *
 * This software was written by David Hadka and others.
 * 
 * The use, modification and distribution of this software is governed by the
 * The Pennsylvania State University Research and Educational Use License.
 * You should have received a copy of this license along with this program.
 * If not, contact <dmh309@psu.edu>.
 */
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>
#include <math.h>
#include <mpi.h>
#include "borgmm.h"

#define PI 3.14159265358979323846

int nvars = 14;
int nobjs = 5;

// The evaluation function is defined in the same way as the serial example
// (see dtlz2_serial.c), but is evaluated in parallel by the slave processes.
void dtlz2(double* vars, double* objs, double* consts) {
	int i;
	int j;
	int k = nvars - nobjs + 1;
	double g = 0.0;

	for (i=nvars-k; i<nvars; i++) {
		g += pow(vars[i] - 0.5, 2.0);
	}

	for (i=0; i<nobjs; i++) {
		objs[i] = 1.0 + g;

		for (j=0; j<nobjs-i-1; j++) {
			objs[i] *= cos(0.5*PI*vars[j]);
		}

		if (i != 0) {
			objs[i] *= sin(0.5*PI*vars[nobjs-i-1]);
		}
	}
	usleep(10000);
}

int main(int argc, char* argv[]) {
	 // setting random seed
  	unsigned int seed = atoi(argv[1]);
	int j;
	int rank;
	int NFE = 1000000;
	char outputFilename[256];
	FILE* outputFile = NULL;
	char runtime[256];
	char timing[256];

	// All multi-master runs need to call startup, specify the number of
	// islands (one master per island), and set the runtime limits.
	BORG_Algorithm_ms_startup(&argc, &argv);
	BORG_Algorithm_ms_islands(1);
	//BORG_Algorithm_ms_max_time(0.1);
	BORG_Algorithm_ms_max_evaluations(NFE); 
	// Enable global Latin hypercube initialization to ensure each island
	// gets a well sampled distribution of solutions.
	BORG_Algorithm_ms_initialization(INITIALIZATION_LATIN_GLOBAL);

	// Define the problem.  Problems are defined the same way as the
	// serial example (see dtlz2_serial.c).
	BORG_Problem problem = BORG_Problem_create(nvars, nobjs, 0, dtlz2);

	for (j=0; j<nvars; j++) {
			BORG_Problem_set_bounds(problem, j, 0.0, 1.0);
	}

	for (j=0; j<nobjs; j++) {
			BORG_Problem_set_epsilon(problem, j, 0.01);
	}

	// Get the rank of this process.  The rank is used to ensure each
	// parallel process uses a different random seed.


	// When running experiments, we want to run the algorithm multiple
	// times and average the results.
	
	// Save runtime dynamics to a file.  Each master node will
	// write its local runtime dynamics to this file.  The %%d
	// gets replaced by the index of the master.
	BORG_Algorithm_output_frequency((int)NFE/40);
	sprintf(outputFilename, "./sets/DTLZ2_S%d.set", seed); 
	sprintf(runtime, "./runtime/dtlz2/DTLZ2_S%d.runtime", seed);
	BORG_Algorithm_output_runtime(runtime);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    BORG_Random_seed(37*seed*(rank+1));


		// Run the multi-master Borg MOEA on the problem.
	BORG_Archive result = BORG_Algorithm_ms_run(problem);

		// Only the controller process will return a non-NULL result.
		// The controller aggregates all of the Pareto optimal
		// solutions generated by each master.  Then print the Pareto
		// optimal solutions to the screen.
	if (result != NULL) {
		outputFile = fopen(outputFilename, "w");
		if (!outputFile) {
			BORG_Debug("Unable to open final output file\n");
		}
		BORG_Archive_print(result, outputFile);
		BORG_Archive_destroy(result);
		fclose(outputFile);
	}
	// Shutdown the parallel processes and exit.
	BORG_Algorithm_ms_shutdown();
	BORG_Problem_destroy(problem);
	return EXIT_SUCCESS;
}
